services:
  app:
    build: .
    networks:
      - my_network
    ports:
      - "8080:80"
  # integrating nginx
  nginxwebsvr:
    image: nginx:alpine
    container_name: nginxwebsvr
    ports:
      - "80:80"
  # integrating mysql
  mysqldb:
    image: mysql:8.0
    restart: always
    volumes:
    - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
  
  # integrating git server
  git-server:
    build:
      dockerfile: ./repos/gitserver.Dockerfile
      context: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./repos:/var/www/git
      - ./repos:/keys # if using ssh

networks:
  my_network:
    driver: bridge